version: '3.9'

services:
  tor-browser:
    image: domistyle/tor-browser
    container_name: tor-browser-privado
    ports:
      - "5800:5800"
    shm_size: '2g'
    # MEJORA DE HARDENING
    environment:
      - DISPLAY_WIDTH=1366
      - DISPLAY_HEIGHT=768
      - USER_ID=1000  # EJECUTAR id -u según el resultado en tu linux
      - GROUP_ID=1000 # ejecutar id -g según el resultado en tu linux
    # ME GUSTAN LOS EMOJIS
